### ISSUE TITLE
Issue when create new scene.pck

### ISSUE THREAD

**Issue by AEBus** [xmoeproject/SiglusExtract#1]
Hello, xmoe!

When i try create new scene.pck SiglusExtract send me error:
![](http://i.imgur.com/DkzYFM5.png)
...
okay
i renamed all files from

```
0.__va_effect_ss_cmd_particle.ss
0.__va_effect_ss_cmd_particle.ss.txt
1.ed_akane.ss
1.ed_akane.ss.txt
[...]
158.sys50_ef00_ys11.ss
158.sys50_ef00_ys11.ss.txt
159.sysny_ef00.ss
159.sysny_ef00.ss.txt
```
to
```
__va_effect_ss_cmd_particle.ss0..txt
__va_effect_ss_cmd_particle0..ss
ed_akane.ss1..txt
ed_akane1..ss
[...]
sys50_ef00_ys11.ss158..txt
sys50_ef00_ys11158..ss
sysny_ef00.ss159..txt
sysny_ef00159..ss
```

and wow, SiglusExtract created Scene.pck.new!

okay, i renamed Scene.pck.new to Scene.pck, then launched game, game send me error:
![](http://i.imgur.com/V0hk24S.png)

...

okay, i decided to check the contents of the new scene.pck through the program parsepck.exe
and parsepck.exe send me error:
![](http://i.imgur.com/KL1sM2X.png)

It seems to me that something is not working properly
![](http://i.imgur.com/O7Dhz2S.png)

**Comment by xmoeproject** [comment]
parsepck.exe... really old tool.
Anyway, thx for your report. The next version will fix this bug.

**Comment by AEBus** [comment]
> parsepck.exe... really old tool.

Yes.. i know... but i don't have nothing newer =(
Maybe you can recommend me good tool for extract scripts from scene.pck / editing text / insert text into a scripts / creating new scene.pck?
Can your SiglusExtract insert new text into scripts?

> Anyway, thx for your report.

Your welcome!

> The next version will fix this bug.

It will be nice!

**Comment by xmoeproject** [comment]
The bugs was fixed.

**Comment by xmoeproject** [comment]
ok, now SiglusExtract works fine...
SiglusExtract can extract both scene.pck and ss scripts inside the pck.
As for reapcking text files, I will release the tool tonight or tomorrow.

**Comment by AEBus** [comment]
Thanks! You awesome!
