### ISSUE TITLE
Where can I find the converted files?

### ISSUE THREAD

**Issue by Darken-san** [xmoeproject/SiglusExtract#10]
Sorry for the noob question, I'm very new to this kind of thing.

I got your program running just fine, but when I drop the files on it (like a folder of g00 images that I want to be converted to png), nothing happens after it finishes extracting.

Where can I find those converted files? Or am I supposed to do something else to get them?

**Comment by ichisadashioko** [comment]
It should be in the `__Unpack__` directory. They don't have meaning names though.
