### ISSUE TITLE
请问能否加入对可替代dbs及wmv格式的支持？

### ISSUE THREAD

**Issue by able1214** [xmoeproject/SiglusExtract#11]
因为从Summer Pockets开始很多文本都在dbs文件里，所以为了做不替换源文件的补丁能否考虑加入对dbs2/ds2或其他任何可以替代的格式的支持？
还有就是能否加入对mp4格式的支持，这样就不用进SiglusEngine里把wmv改成mp4了。。。
谢谢~

**Comment by xmoeproject** [comment]
dbs文件支持已经在ver 0.1.0.6 中完成。
mp4格式的支持不太明白是什么意思。

**Comment by able1214** [comment]
![wmv](https://user-images.githubusercontent.com/32001378/84613310-3ff09600-ae80-11ea-9337-6f6e0c7fa2d8.png)
就是这个意思。。。一般汉化完都是吧这里改成mp4，所以汉化完的op等视频就不会覆盖原来的wmv。
上面的dbs其实也是为了想说汉化玩的文件能不用覆盖原始文件而对另一种可替代文件格式的支持。
![$S)Z{}AST`SKD(9(K__14KY](https://user-images.githubusercontent.com/32001378/84613525-9cec4c00-ae80-11ea-800d-637e4fd63d59.png)
就像SiglusExtract本来就能载入g01、dat2、pck2和om2这些文件一样，我的意思就是是能不能多加入两种格式的支持：不会覆盖dbs文件和wmv格式的支持（比如dbs2/dbc/ds2、mp4）
可能我上面表达得不是很清楚不好意思~

**Comment by AyamiKaze** [comment]
> > mp4格式的支持不太明白是什么意思。
> 
> 首先多谢更新~
> 可能我上面表达得不是很清楚：
> ![wmv](https://user-images.githubusercontent.com/32001378/84613310-3ff09600-ae80-11ea-9337-6f6e0c7fa2d8.png)
> 就是这个意思。。。一般汉化完都是吧这里改成mp4，所以汉化完的op等视频就不会覆盖原来的wmv。
> 上面的dbs其实也是为了想说汉化完的文件能不用覆盖原始文件而对另一种可替代文件格式的支持。
> ![$S)Z{}AST`SKD(9(K__14KY](https://user-images.githubusercontent.com/32001378/84613525-9cec4c00-ae80-11ea-800d-637e4fd63d59.png)
> 就像SiglusExtract本来就能载入g01、dat2、pck2和om2这些文件一样，我的意思就是是能不能多加入两种格式的支持：不会覆盖dbs文件和wmv格式的支持（比如dbs2/dbc/ds2、mp4）
> 希望这次解释清楚了。。。

wmv的话没这个必要，你可以自己压制。
至于g01和dat2这些后缀名其实你看看源码就知道是怎么实现的了。所以没必要去支持mp4.
如果你想不完全覆盖源文件的话，可以尝试自己去hook函数换掉文件名，这非常容易去实现。

**Comment by xmoeproject** [comment]
https://github.com/xmoeproject/SiglusExtract/commit/e1e7ec013b54118029181b09a254dec1d39983de
来晚了

**Comment by able1214** [comment]
> [e1e7ec0](https://github.com/xmoeproject/SiglusExtract/commit/e1e7ec013b54118029181b09a254dec1d39983de)
> 来晚了

0.1.0.6版对应的还是SiglusCfg.ini吧，能否编译下新版本把对SiglusCfg.json的支持加进去
