### ISSUE TITLE
summer pockets rb

### ISSUE THREAD

**Issue by rinnow** [xmoeproject/SiglusExtract#12]
I tried to extract CGs in this game but did have to merge it myself. Are there any ways to make g00 to jpg with transparent data or merge it by siglus extract itself?

**Comment by ichisadashioko** [comment]
What do you mean by "merging"? JPEG does not support transparency so you will probably have to export the CG as PNG format instead.

**Comment by rinnow** [comment]
Must be it. When I tried it in png it went well.
Thanks.
