### ISSUE TITLE
How to build SiglusExtract.dll and SiglusEngine.exe from source with Cmake ?

### ISSUE THREAD

**Issue by ToosakaRin1412** [xmoeproject/SiglusExtract#13]
I'm very new to this kind of thing. How to make SiglusExtract.dll and SiglusExtract.exe ? i have tried use Cmake but i dont understand to use it. i think you should add SiglusExtract.dll and SiglusExtract.exe to this repository.

**Comment by xmoeproject** [comment]
SiglusEngine ONLY works on Windows platform therefore SiglusExtract only supports Windows.
All cmake scripts will be converted to  *.sln
If you prefer a command-line tool, you can use msbuild to build SiglusExtract.

**Comment by ichisadashioko** [comment]
I will try to build it and create a building guide for newcomers.

**Comment by ichisadashioko** [comment]
@ToosakaRin1412 Why do want to build with `cmake`?
