### ISSUE TITLE
Cant find both exe and dll

### ISSUE THREAD

**Issue by kelvinclub** [xmoeproject/SiglusExtract#14]
had browsing all the files and i didnt found SiglusExtract.exe and SiglusExtract.dll, any idea where are them?

**Comment by xmoeproject** [comment]
Build by yourself or download from the release page

**Comment by kelvinclub** [comment]
yea i downloaded from the page, but didn't see both of these files

**Comment by xmoeproject** [comment]
[0.1.0.6](https://github.com/xmoeproject/SiglusExtract/releases/tag/0.1.0.6)
