### ISSUE TITLE
アインシュタインより愛を込めて

### ISSUE THREAD

**Issue by rinnow** [xmoeproject/SiglusExtract#16]
I tried to extract アインシュタインより愛を込めて but it doesn't work for the trial version.
I really do appriciate it if you correspond for this game.

https://glovety.product.co.jp/#top
you can get the trial version from here just in case.

**Comment by rinnow** [comment]
worked for product

**Comment by xmoeproject** [comment]
fix for the trial version.
https://github.com/xmoeproject/SiglusExtract/commit/06846002638c171cf0084d110ac9a7420baf0ecd

**Comment by xmoeproject** [comment]
As usual, the trial version didn't need the private key to decrypt.
