### ISSUE TITLE
Couldn't extract Scene.pck (Hoshi Ori Yume Mirai)

### ISSUE THREAD

**Issue by MishaIac** [xmoeproject/SiglusExtract#19]
VN: Hoshi Ori Yume Mirai (with the English patch from Tsurezure Scans)
VNDB: https://vndb.org/v14265

I want to extract the script from the English Scene.pck, but the following error appears:
![image](https://user-images.githubusercontent.com/47920105/102383434-31706c00-3fd4-11eb-9ed7-3509deb4a03e.png)

When unpacking the Japanese Scene.pck, there is no such error, and everything unpacked successfully.

**Comment by MishaIac** [comment]
Fixed

**Comment by leminhyen2** [comment]
@MishaIac What was your solution for this? I have the same issue too

**Comment by MishaIac** [comment]
> @MishaIac What was your solution for this? I have the same issue too

I used this: https://github.com/yanhua0518/GALgameScriptTools/tree/master/SiglusEngine

**Comment by leminhyen2** [comment]
oh thanks, you replied so fast. Do you have an email or some social media (ie. Discord). I would love to talk with you about how you solve this
