### ISSUE TITLE
ScriptRepacker - Index error(to large)

### ISSUE THREAD

**Issue by AEBus** [xmoeproject/SiglusExtract#2]
When i try repack script, with contain russian text, all ok. But for some reason (russian text incorrectly shown in the game, a large distance between letters
![](http://i.imgur.com/UnKEnzK.png)
) i use modified font with half-widht katakana and latin symbols, so text looks something like this:

>ﾆｲｫA ｱOｫEｿAｰCｽ ｱPEｬﾉｮｯ OｱﾋｮﾈｮCﾋｮｵﾉｹｯ ｽ?
>ｲ ﾈEﾉｽ ﾉE XｿAﾋｮﾋ Cｮｰｹ ｿOｰｮ ｿEPﾉｲﾋｺCｽ ｿ ｱPEｬﾉEE COCﾋOｽﾉｮE.
>ｱO ﾆPAｯﾉEｯ ﾈEPE, ｱOﾆA ｽ ﾉE CﾈOｪｲ ﾆOE ｿ ｵｧﾈ ｲｩEｫｮﾋｺCｽ.
>ｱOﾆA ﾉE CﾈOｪｲ ﾉAﾆOﾉEｴ ｿｭｫOXﾉｲﾋｺ C OｩｰEｪｵEﾉｮEﾈ.
>ｫO ﾋEX ｱOP ｽ ﾉE ｲCｱOﾆOｼCｺ.
>ECｰｮ ｱOｫｲﾈAﾋｺ, CEｯｵAC ﾆAｬEﾋCｽ, ｵﾋO ｽ ﾉｮﾆOｪｫA ｮ ﾉE ｩｹｰ ﾋAﾆｮﾈ ｲｬ ｵEPECｵｲP Oｬｮｿｰｧﾉﾉｹﾈ ｮ PAｫOCﾋﾉｹﾈ.

So, i replace all russian symbols to half-width katakana and latin symbols (file containt the same amount syblos and lines as a russian) ScriptRepacker send me this error:
![](http://i.imgur.com/Ap36j1i.png)

But ssinsert work fine

**Comment by haoqihu** [comment]
After i translate and repack;Game can run but when arrive the translated parts,something is wrong;
Warning window shows that “.ss が見つかりませんでした。”;
About extracted text,there are many game's control character(such as _Black.#N.▼);And the end part of text looks like some cg's adresss(such as cg_3p03_0742);
i want to know is the problem caused by these character?how to handle it?

**Comment by xmoeproject** [comment]
Repacking issue was fixed and the tool was updated.
As for font distance issue, SiglusEngine only support fixed-width font.

Please update SiglusExtract.dll and try follow steps below:
1.Please create a file named "SiglusEnginePatch.ini" in your game root directory.
2.Type only one char "P" in this file. 
3.Save file.

this program will automatically do some patches.
this feature maybe unstable.

**Comment by AEBus** [comment]
>Please update SiglusExtract.dll and try follow steps below:
>1.Please create a file named "SiglusEnginePatch.ini" in your game root directory.
>2.Type only one char "P" in this file.
>3.Save file.
>this program will automatically do some patches.

After that i need to create universal patch through SiglusExtract, yes? And run game through SignusEbgine_Patch?
But nothing happens. No difference, there is this ini file, or it is not.

**Comment by AEBus** [comment]
Fix distance between symbols and set font result:

![](https://cdn.discordapp.com/attachments/332382779448885251/345953937091723264/123.png)

**Comment by xmoeproject** [comment]
Now SiglusExtract(UniversalPatcher) using a more stable method to bypass font distance check.
