### ISSUE TITLE
About the runtime environment of SiglusExtract

### ISSUE THREAD

**Issue by liekong** [xmoeproject/SiglusExtract#20]
SiglusExtract是否不支持win10环境下运行？
双击打开没有任何反应，拖入游戏主程序文件会提示“Fail to Create Process!”

**Comment by xmoeproject** [comment]
1.windows有良好的兼容性
2.SiglusExtract没有任何理由不兼容win10
3.SiglusExtract是开源工程，可以自己分析问题所在
4.这种情况极有可能是被杀软给干掉了

**Comment by liekong** [comment]
我把windows defender关闭了，肯定不是杀毒软件的问题，
而且如果是杀毒软件的问题，软件连运行都不发运行，怎么会有错误提示。
也有别的Issue反应了win10无法运行的问题，
看来只能搞个VS自己调试看看了

**Comment by xmoeproject** [comment]
![image](https://user-images.githubusercontent.com/10909416/105126679-3caa4080-5b1a-11eb-8ed6-55b25f3f6227.png)

在Loader.cpp中：
`MessageBoxW(NULL, L"SiglusExtract : Failed to Create Process!", L"SiglusExtract", MB_OK | MB_ICONERROR);`
只有进程创建失败了才会有该提示，任务管理器是定时刷新的，人眼监控不可取。
首先先保证SiglusExtract文件在游戏目录中，和游戏主程序位于同一目录，如果没别的kernel module做拦截，那么首先排查你的游戏主程序真的就是SiglusEngine.exe并且没有被别人的软件给patch过。
另外不支持steam系列的游戏，也没有理由去支持。

**Comment by liekong** [comment]
哦，确实不是SiglusEngine，是Reallive的，版本是1.5.3.3，这点我倒是忘记说了

**Comment by liekong** [comment]
这样，那是我弄错了，感谢
