### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by God-Dead** [xmoeproject/SiglusExtract#23]
It popped up as a  genericRXAA-AA!687FCC79A7D2 virus. Can I get some confirmation that this isn't a trojan before I use it?

**Comment by mailwl** [comment]
i doubt it. it injects to process, and it looks like a virus

**Comment by xmoeproject** [comment]
SiglusExtract is an open-source project, and you can build it yourself if you don't trust the pre-built binaries.
SiglusExtract requires some technique to inspect the process, which behaviors like a virus.
