### ISSUE TITLE
issue about repack text

### ISSUE THREAD

**Issue by haoqihu** [xmoeproject/SiglusExtract#3]
After i translate and repack;Game can run but when arrive the translated parts,something is wrong;
Warning window shows that “.ss が見つかりませんでした。”;
About extracted text,there are many game's control character(such as _Black.#N.▼);And the end part of text looks like some cg's adresss(such as cg_3p03_0742);
i want to know is the problem caused by these character?how to handle it?

**Comment by xmoeproject** [comment]
plz don't edit these control characters in any case.
This issue was fixed and  the new version of tool was updated.
thanks for your bug report.

**Comment by haoqihu** [comment]
tks for your quick response;but may I ask if the translated text is shorter than original text (it causes the change of control characters' location);which character could be fine to fill the gap?
