### ISSUE TITLE
有关SiglusEngine引擎rewrite如何强制渲染1080p的问题

### ISSUE THREAD

**Issue by xldsdr124** [xmoeproject/SiglusExtract#7]
rewrite是720p画质在高分辨率下电脑显得模糊有点遗憾，我想用waifu2x 同类topazai来处理成1080p的，但是遇到了一个问题，当我把测试素材打包回g00文件，画面内始终“锁定”1280x720分辨率，当我更改游戏分辨率为1920x1080，g00 cg那一张超出了很多部分被明显的放大，看出整体是1280锁死的，请教下这个问题有什么解决办法吗

**Comment by xmoeproject** [comment]
首先，游戏脚本的UI坐标非常可能是以720为基准写死，我多年前解析过siglus脚本（不完整），所以我也不确定。你要这样做我觉得也许一开始的思路就不太对。

**Comment by xldsdr124** [comment]
### 我想尝试一下，之前接触一个引擎的开发里面的素材是缩放的，不确定这里是什么结构，因为拆了下rewrite立绘，发现立绘非常大，应该是按1920设计的，我想把cg和系统ui匹配下

**Comment by xmoeproject** [comment]
坐标这块你可以参考一下xclannad里面的解析，也不是一两句话就能说清楚的，xclannad是多年前民间逆向reallive搞出来的，和原始引擎相比很多都不同但是很多逻辑是类似的。如果你非要以修改游戏资源的形式来做，我建议先解析出脚本格式，里面有很多坐标都得改动。

**Comment by xldsdr124** [comment]
谢谢回复，我正在尝试使用extract解包rewrite+ scene.pck，但是在拖入当中并提示程序停止运行

**Comment by xmoeproject** [comment]
给个crash或者windbg的截图

**Comment by xldsdr124** [comment]
![Uploading TIM图片20190509175442.png…]()

**Comment by xldsdr124** [comment]
![TIM截图20190509175340](https://user-images.githubusercontent.com/26106045/57444837-a8377600-7283-11e9-8747-f6c1df35710f.png)

**Comment by xldsdr124** [comment]
当我拖入Scene.pck或gameexe.dat时报错

**Comment by xldsdr124** [comment]
不知道是不是没配置好，
dmp是Loading unloaded module list
.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(1b04.28b4): Access violation - code c0000005 (first/second chance not available)
eax=00000000 ebx=7fe1e000 ecx=00000008 edx=73810000 esi=00000000 edi=73811360
eip=73812a61 esp=1369fe04 ebp=1369fe0c iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
gpapi!CGPSvcBindingHandleFactory::Destroy+0xd:
73812a61 8b3488          mov     esi,dword ptr [eax+ecx*4] ds:002b:00000020=????????

**Comment by xmoeproject** [comment]
最好先.reload 然后再kn一下，晚上有空我看看
